# Generated by Django 3.2.12 on 2022-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.BooleanField()),
                ('feb', models.BooleanField()),
                ('march', models.BooleanField()),
                ('april', models.BooleanField()),
                ('may', models.BooleanField()),
                ('june', models.BooleanField()),
                ('july', models.BooleanField()),
                ('august', models.BooleanField()),
                ('sept', models.BooleanField()),
                ('oct', models.BooleanField()),
                ('nove', models.BooleanField()),
                ('dec', models.BooleanField()),
            ],
        ),
    ]
