# Generated by Django 3.2.12 on 2022-03-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthtable',
            name='tittless',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
