# Generated by Django 3.2.12 on 2022-03-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_accounting', '0002_monthtable_tittless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthtable',
            name='feb',
            field=models.BooleanField(editable=False),
        ),
    ]
