# Generated by Django 3.2.12 on 2022-03-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_accounting', '0004_auto_20220317_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasa',
            name='kasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
