# Generated by Django 3.2.12 on 2022-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_accounting', '0005_alter_kasa_kasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasa',
            name='kasa_2',
            field=models.FloatField(default=0.0),
        ),
    ]
